---
__Universidad Tecnológica Nacional, Buenos Aires__\
__Ingeniería Industrial__\
__Cátedra de Investigación Operativa__\
__Autor: Rodrigo Maranzana__, Rmaranzana@frba.utn.edu.ar

---

# Ejercicio 5

La cervecería más importante del mundo (Guiness) ha contratado a un analista de investigación de operaciones para analizar su posición en el mercado. Están preocupados en especial por su mayor competidor (Heineken). El analista piensa que el cambio de marca se puede modelar como una cadena de Markov incluyendo tres estados, los estados *G* y *H* representan a los clientes que beben cerveza producida por las mencionadas cervecerías y el estado *I* representa todas las demás marcas. Los datos se toman cada mes y el analista ha construido la siguiente matriz de transición de los datos históricos.

| /| G | H  | I  |
|--:|--:|---:|---:|
| G |0.7|0.2 |0.1 |
| H |0.2|0.75|0.05|
| I |0.1|0.1 |0.8 |


## Resolución

Importamos las librerías que vamos a usar:

In [8]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

Cargamos la Matriz de transición T con la librería *Numpy*. 

Recordemos que lo tenemos que hacer de la siguiente forma: armamos una "lista de listas". Lo que estamos creando es una Matriz, donde cada lista es una fila. Luego, esto lo convertimos en un array de *Numpy* ya que nos

In [9]:
# Ingresamos la matriz de transición:
T = np.array([[0.70, 0.20, 0.10], 
              [0.20, 0.75, 0.05], 
              [0.10, 0.10, 0.80]])

# Printeamos la matriz de transición T:
print(f'Matriz de transición: \n{T}')

Matriz de transición: 
[[0.7  0.2  0.1 ]
 [0.2  0.75 0.05]
 [0.1  0.1  0.8 ]]


In [10]:
# Construir matriz A y vector B:
A = (np.transpose(T) - np.identity(3))
B = np.zeros(3)

# Printeamos la Matriz A y vector B
print(f'Matriz A relacionada al sistema lineal de ecauciones: \n{A}\n')

print(f'Vector B relacionado al sistema lineal de ecuaciones: \n{B}')

Matriz A relacionada al sistema lineal de ecauciones: 
[[-0.3   0.2   0.1 ]
 [ 0.2  -0.25  0.1 ]
 [ 0.1   0.05 -0.2 ]]

Vector B relacionado al sistema lineal de ecuaciones: 
[0. 0. 0.]


In [11]:
# Agregar sumatoria de probabilidades:
sum_prob = np.array([[1, 1, 1]])

A = np.concatenate((A, sum_prob), axis=0)

B = np.append(B, 1)


# Printeamos la Matriz A y vector B:
print(f'Matriz A: \n{A}\n')

print(f'Vector B: \n{B}')

Matriz A: 
[[-0.3   0.2   0.1 ]
 [ 0.2  -0.25  0.1 ]
 [ 0.1   0.05 -0.2 ]
 [ 1.    1.    1.  ]]

Vector B: 
[0. 0. 0. 1.]


In [12]:
# Resolvemos por mínimos cuadrados:
X, _, _, _ = np.linalg.lstsq(A, B)

# Printeamos la solución
print(f'Solución del sistema lineal de ecuaciones: \n{X}')

Solución del sistema lineal de ecuaciones: 
[0.34615385 0.38461538 0.26923077]
